USE [master]
GO
/****** Object:  Database [ProjectDataBase]    Script Date: 5/7/2024 3:47:34 AM ******/
CREATE DATABASE [ProjectDataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjectDataBase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ProjectDataBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProjectDataBase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ProjectDataBase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ProjectDataBase] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjectDataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ProjectDataBase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ProjectDataBase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ProjectDataBase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ProjectDataBase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ProjectDataBase] SET ARITHABORT OFF 
GO
ALTER DATABASE [ProjectDataBase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ProjectDataBase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ProjectDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ProjectDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ProjectDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ProjectDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ProjectDataBase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ProjectDataBase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ProjectDataBase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ProjectDataBase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ProjectDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ProjectDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ProjectDataBase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ProjectDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ProjectDataBase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ProjectDataBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ProjectDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ProjectDataBase] SET RECOVERY FULL 
GO
ALTER DATABASE [ProjectDataBase] SET  MULTI_USER 
GO
ALTER DATABASE [ProjectDataBase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ProjectDataBase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ProjectDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ProjectDataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ProjectDataBase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ProjectDataBase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ProjectDataBase', N'ON'
GO
ALTER DATABASE [ProjectDataBase] SET QUERY_STORE = ON
GO
ALTER DATABASE [ProjectDataBase] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ProjectDataBase]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 5/7/2024 3:47:35 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Users] ([Id], [FirstName], [LastName], [UserName], [Password], [Email]) VALUES (1, N'Somaye', N'Shirzad', N'Ssh', N'Ssh12345', N'Somaye_Shirzad@yahoo.com')
GO
INSERT [dbo].[Users] ([Id], [FirstName], [LastName], [UserName], [Password], [Email]) VALUES (2, N'Ali', N'Alavi', N'Ali', N'Ali12345', N'Ali-Alavi@yahoo.com')
GO
/****** Object:  StoredProcedure [dbo].[uspGetUser]    Script Date: 5/7/2024 3:47:35 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[uspGetUser]
(
    @userName nvarchar(50)=null,
    @password nvarchar(100)=null
)
AS
BEGIN
    SET NOCOUNT ON

	IF(@userName IS NULL AND @password IS NULL)
	BEGIN
	  SELECT Id,FirstName,LastName,UserName,Password,Email
       FROM dbo.Users
	END
	ELSE
	BEGIN
    SELECT Id,FirstName,LastName,UserName,Password,Email
       FROM dbo.Users
       WHERE Username = @userName AND Password = @password;
	END
END
GO
USE [master]
GO
ALTER DATABASE [ProjectDataBase] SET  READ_WRITE 
GO
